services:
  botchat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_SUPABASE_URL: ${PUBLIC_SUPABASE_URL}
        PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY}
    environment:
      VERCEL_URL: ${VERCEL_URL}
      PUBLIC_SUPABASE_URL: ${PUBLIC_SUPABASE_URL}
      OPENAI_CONVERSATION_SUMMARY_MODEL: ${OPENAI_CONVERSATION_SUMMARY_MODEL}
      PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3202:3000"
    restart: unless-stopped
